// The ONE central media pipeline. Every provider feeds this; nothing bypasses it.
//
// STAGES, IN ORDER, EACH ABLE TO STOP THE CANDIDATE DEAD
// ------------------------------------------------------
//   1. discovery            provider returns rights-free hits
//   2. entity validation    is this a picture of THAT product? ambiguous = stop
//   3. provenance           resolve the item's own source page for primary evidence
//   4. rights verification  what the evidence supports; conflict = stop
//   5. duplicate reconciliation  the same file from two providers, and the case
//                           where the two disagree about its licence
//   6. quality / ranking     choose among the survivors, and record why
//   7. publication validation  prove the proposed row does NOT clear the
//                           publication gate, because the engine must never
//                           produce something that does
//
// WHY STAGE 7 EXISTS WHEN THE ENGINE NEVER PUBLISHES
// ---------------------------------------------------
// Because "the engine never publishes" is a property of today's code, and this
// makes it a property that is CHECKED. `validateEnginePublicationSafety()`
// takes the exact row the pipeline would write and asserts that
// evaluatePublishEligibility() refuses it. If a future change made engine
// output publishable, that assertion fails in the unit tests rather than on
// the live site.
//
// FAIL-CLOSED IS THE DEFAULT RETURN, NOT AN EXCEPTION PATH
// --------------------------------------------------------
// Every early return in this file is a refusal. There is no branch that
// accepts a candidate for lack of a reason to reject it.
//
// Pure except `runAcquisitionPipeline`, which drives providers over the network.

import { evaluatePublishEligibility } from "../rights.ts";
import { evaluateProvenance, type ProvenanceAsset } from "../provenance.ts";
import { assessEntityMatch, type CandidateDescriptor, type EntityMatchAssessment } from "./entity-match.ts";
import { verifyRights, licencesAgree } from "./rights-verification.ts";
import { rankCandidates, type RankableCandidate, type RankingContext, type RankingResult } from "./ranking.ts";
import {
  classifySearchOutcome,
  legacyStatusFor,
  OUTCOME_MEANINGS,
  type ProviderEpisode,
  type SearchOutcome,
} from "./outcome.ts";
import type { SubjectIdentity } from "./query-expansion.ts";
import { expandQueries } from "./query-expansion.ts";
import {
  ENGINE_MAX_RIGHTS_STATUS,
  type DiscoveredCandidate,
  type MediaProvider,
  type ProvenanceRecord,
  type ProviderApproval,
  type ProviderOutcome,
  type ProviderQuery,
  type RightsAssessment,
} from "./types.ts";

// ---------------------------------------------------------------------------
// Per-candidate evaluation (stages 2-4)
// ---------------------------------------------------------------------------

export type RejectionCode =
  | "entity_mismatch"
  | "entity_ambiguous"
  | "provenance_unresolvable"
  | "rights_restricted"
  | "rights_conflicting"
  | "rights_incomplete"
  | "synthetic_imagery"
  | "unsupported_media_type"
  | "quality_below_floor"
  | "duplicate_of_better"
  | "duplicate_licence_conflict"
  | "provider_outage"
  | "provider_malformed";

// ---------------------------------------------------------------------------
// Synthetic imagery — the rule that has nothing to do with rights
// ---------------------------------------------------------------------------

/**
 * Phrases that mean the image was generated rather than photographed.
 *
 * Commons hosts a growing volume of AI imagery under impeccable CC0 tags. A
 * CC0 "photograph" of a PS5 Pro generated by a diffusion model is perfectly
 * licensed and completely false, and it is the single most dangerous candidate
 * class this pipeline can encounter — the licence check passes, the entity
 * check passes (the model drew the right-looking object), and the result is a
 * fabricated depiction of a real product on a page that implies documentation.
 *
 * docs/product-media-strategy.md rule 2: "Never a generated image presented
 * as, or mistakable for, a photograph of a real product." This enforces it
 * before acquisition rather than hoping someone notices later.
 */
const SYNTHETIC_MARKERS: [RegExp, string][] = [
  [/\bai[\s-]?generated\b/i, "described as AI-generated"],
  [/\bgenerated (?:by|with|using) (?:ai|an ai|a neural)/i, "described as generated by AI"],
  [/\bstable diffusion\b/i, "names Stable Diffusion"],
  [/\bmidjourney\b/i, "names Midjourney"],
  [/\bdall[\s·.-]?e\b/i, "names DALL-E"],
  [/\bflux\.1\b/i, "names FLUX.1"],
  [/\bimagen\b/i, "names Imagen"],
  [/\bgemini (?:image|nano banana)\b/i, "names a Gemini image model"],
  [/\bfirefly\b/i, "names Adobe Firefly"],
  [/\btext[\s-]?to[\s-]?image\b/i, "described as text-to-image output"],
  [/\bsynthetic (?:image|photo|photograph)\b/i, "described as a synthetic image"],
  [/\bcategory:ai[\s-]?generated/i, "member of an AI-generated category"],
  [/\bcategory:images generated by/i, "member of a generated-images category"],
];

export type SyntheticVerdict = { synthetic: boolean; marker: string | null; detail: string };

/**
 * Does anything at source indicate this image was generated?
 *
 * Fails closed on the marker, not on a judgement of how real it looks. There
 * is no reliable way to tell a good generated product render from a photograph
 * by inspection, so the only defensible rule is: if the source says or hints
 * it was generated, it is out — regardless of how good the licence is.
 */
export function detectSyntheticImagery(
  descriptor: CandidateDescriptor,
  provenance: ProvenanceRecord | null
): SyntheticVerdict {
  const hay = [
    descriptor.title,
    descriptor.fileName ?? "",
    descriptor.descriptionText ?? "",
    ...descriptor.categories,
    ...(provenance?.evidence.map((e) => e.detail) ?? []),
    provenance?.creator ?? "",
  ].join(" \n ");

  for (const [pattern, why] of SYNTHETIC_MARKERS) {
    if (pattern.test(hay)) {
      return {
        synthetic: true,
        marker: why,
        detail:
          `Source metadata ${why}. A generated image of a real product is a fabricated depiction however good its ` +
          "licence is, and this site never publishes one as, or mistakable for, product photography.",
      };
    }
  }
  return { synthetic: false, marker: null, detail: "Nothing at source indicates the image was generated." };
}

/**
 * Minimum long edge for an image the engine will archive as a product photo.
 *
 * Not a rights rule and not arbitrary: below this a hero visibly softens on a
 * 2x display, and an upscaled small image looks like something taken without
 * permission even when it was not. A candidate under the floor is reported as
 * a finding rather than acquired, so the requirement stays open and honest
 * instead of being closed with something unusable.
 */
export const MIN_ACQUIRE_LONG_EDGE = 800;

/**
 * File types that can be a product PHOTOGRAPH.
 *
 * The first live run made the case for this gate better than any argument
 * would have: searching for the Intel Core Ultra 9 285K accepted three
 * candidates, and all three were **`.stl` files** — 3D-printable models of the
 * processor. Correct product, CC0, high entity confidence, and not a
 * photograph in any sense. Commons is a media repository, not an image
 * library: it holds STL meshes, PDFs, SVGs, OGV video and MIDI, and every one
 * of them can carry an impeccable licence.
 *
 * SVG is excluded deliberately rather than by oversight. A vector file naming
 * a product is a logo — the "Galaxy S26 Ultra" hit in the earlier audit was a
 * Samsung logo SVG — and a logo is never a photograph of a device.
 */
const ACQUIRABLE_MIME_TYPES = new Set(["image/jpeg", "image/png", "image/webp"]);

export type CandidateEvaluation = {
  key: string;
  descriptor: CandidateDescriptor;
  provider: ProviderApproval;
  /** The last stage this candidate reached. */
  stageReached: "entity" | "provenance" | "rights" | "duplicate" | "ranking";
  accepted: boolean;
  rejection: { code: RejectionCode; message: string } | null;
  entityMatch: EntityMatchAssessment | null;
  provenance: ProvenanceRecord | null;
  rights: RightsAssessment | null;
};

/**
 * Stages 2-4 for one candidate. Pure — the provenance was already fetched.
 *
 * Entity matching runs FIRST, before rights are even looked at. Verifying the
 * licence of a photograph of the wrong product is wasted work at best, and at
 * worst it produces a beautifully documented wrong answer.
 */
export function evaluateCandidate(input: {
  identity: SubjectIdentity;
  descriptor: CandidateDescriptor;
  provenance: ProvenanceRecord | null;
  /** Non-ok means resolution failed; that is a rejection, never a pass. */
  resolveOutcome: ProviderOutcome;
  provider: ProviderApproval;
  key: string;
}): CandidateEvaluation {
  const base = {
    key: input.key,
    descriptor: input.descriptor,
    provider: input.provider,
    entityMatch: null as EntityMatchAssessment | null,
    provenance: null as ProvenanceRecord | null,
    rights: null as RightsAssessment | null,
  };

  // --- Stage 2: entity validation -----------------------------------------
  const entityMatch = assessEntityMatch(input.identity, input.descriptor);
  base.entityMatch = entityMatch;

  if (entityMatch.verdict === "rejected") {
    return {
      ...base, stageReached: "entity", accepted: false,
      rejection: { code: "entity_mismatch", message: entityMatch.reason },
    };
  }
  if (entityMatch.verdict === "ambiguous") {
    return {
      ...base, stageReached: "entity", accepted: false,
      rejection: { code: "entity_ambiguous", message: entityMatch.reason },
    };
  }

  // --- Stage 3: provenance resolution --------------------------------------
  if (input.resolveOutcome.status !== "ok" || !input.provenance) {
    const detail =
      input.resolveOutcome.status === "ok"
        ? "resolution reported success but returned no provenance record"
        : `${input.resolveOutcome.status}: ${"detail" in input.resolveOutcome ? input.resolveOutcome.detail : ""}`;
    const code: RejectionCode =
      input.resolveOutcome.status === "outage" || input.resolveOutcome.status === "rate_limited"
        ? "provider_outage"
        : input.resolveOutcome.status === "malformed"
          ? "provider_malformed"
          : "provenance_unresolvable";
    return {
      ...base, stageReached: "provenance", accepted: false,
      rejection: {
        code,
        message:
          `Could not resolve this candidate's own source page (${detail}). A candidate whose provenance could not ` +
          "be read is not a candidate — an unavailable check is a stop, never a skip.",
      },
    };
  }
  base.provenance = input.provenance;

  // --- Stage 4: rights verification ----------------------------------------
  const rights = verifyRights(input.provenance);
  base.rights = rights;

  if (rights.evidenceClass === "restricted") {
    return {
      ...base, stageReached: "rights", accepted: false,
      rejection: { code: "rights_restricted", message: rights.narrative },
    };
  }
  if (rights.evidenceClass === "evidence_conflicting") {
    return {
      ...base, stageReached: "rights", accepted: false,
      rejection: { code: "rights_conflicting", message: rights.narrative },
    };
  }
  if (rights.evidenceClass === "evidence_incomplete") {
    return {
      ...base, stageReached: "rights", accepted: false,
      rejection: { code: "rights_incomplete", message: rights.narrative },
    };
  }

  // --- Stage 3b: is it even a photograph-shaped file? ----------------------
  const mime = (input.provenance.mimeType ?? "").toLowerCase();
  if (!ACQUIRABLE_MIME_TYPES.has(mime)) {
    return {
      ...base, stageReached: "provenance", accepted: false,
      rejection: {
        code: "unsupported_media_type",
        message:
          `Media type "${mime || "unknown"}" cannot be a product photograph. Acquirable types are ` +
          `${[...ACQUIRABLE_MIME_TYPES].join(", ")}. A correctly-licensed 3D model, PDF, vector logo or video of the ` +
          "right product is still not a photograph of it.",
      },
    };
  }

  // --- Stage 4b: synthetic imagery -----------------------------------------
  // Deliberately AFTER rights, so the log shows a generated image was refused
  // on its own merits rather than being lumped in with a licence failure.
  const synthetic = detectSyntheticImagery(input.descriptor, input.provenance);
  if (synthetic.synthetic) {
    return {
      ...base, stageReached: "rights", accepted: false,
      rejection: { code: "synthetic_imagery", message: synthetic.detail },
    };
  }

  // --- Stage 4c: quality floor ---------------------------------------------
  const longEdge = Math.max(input.provenance.width ?? 0, input.provenance.height ?? 0);
  if (longEdge < MIN_ACQUIRE_LONG_EDGE) {
    return {
      ...base, stageReached: "rights", accepted: false,
      rejection: {
        code: "quality_below_floor",
        message:
          `Long edge ${longEdge || "unknown"}px is below the ${MIN_ACQUIRE_LONG_EDGE}px floor for an archived product ` +
          "photograph. The licence is fine; the picture is not usable. Recording this as a finding keeps the " +
          "requirement honestly open instead of closing it with something that will have to be replaced.",
      },
    };
  }

  return { ...base, stageReached: "rights", accepted: true, rejection: null };
}

// ---------------------------------------------------------------------------
// Stage 5: duplicate reconciliation across providers
// ---------------------------------------------------------------------------

/**
 * Collapse candidates that are the SAME FILE reached through different
 * providers, and refuse the whole group when they disagree about its licence.
 *
 * The disagreement case is the important one and it fails closed for both
 * copies. If provider A says CC BY 4.0 and provider B says CC BY-NC for
 * byte-identical content, one of them is wrong about the terms we would be
 * relying on. Picking the friendlier reading is how a NonCommercial photograph
 * ends up on a commercial page; picking the stricter one silently discards a
 * possibly-fine asset while leaving the underlying contradiction unexamined.
 * Blocking both and saying so is the only honest outcome.
 */
export function reconcileDuplicates(evaluations: CandidateEvaluation[]): CandidateEvaluation[] {
  const groups = new Map<string, CandidateEvaluation[]>();
  const ungrouped: CandidateEvaluation[] = [];

  for (const e of evaluations) {
    const hash = e.provenance?.contentHash;
    if (!e.accepted || !hash) {
      ungrouped.push(e);
      continue;
    }
    const list = groups.get(hash) ?? [];
    list.push(e);
    groups.set(hash, list);
  }

  const out: CandidateEvaluation[] = [...ungrouped];

  for (const [hash, group] of groups) {
    if (group.length === 1) {
      out.push(group[0]);
      continue;
    }

    // Same bytes, different licence claims?
    const licences = group.map((g) => g.provenance!.licenceDeclared ?? g.provenance!.licenceMetadata);
    const allAgree = licences.every((l) => licencesAgree(l, licences[0]));
    if (!allAgree) {
      const summary = group
        .map((g) => `${g.provider.label} says "${g.provenance!.licenceDeclared ?? g.provenance!.licenceMetadata}"`)
        .join("; ");
      for (const g of group) {
        out.push({
          ...g,
          stageReached: "duplicate",
          accepted: false,
          rejection: {
            code: "duplicate_licence_conflict",
            message:
              `Byte-identical content (sha256 ${hash.slice(0, 12)}…) carries CONFLICTING licence metadata across providers: ${summary}. ` +
              "One of these is wrong about the terms we would be relying on. Both copies are refused — the safe-looking " +
              "reading is not evidence, and quietly taking the stricter one would hide the contradiction instead of surfacing it.",
          },
        });
      }
      continue;
    }

    // Agreeing duplicates: keep the copy with the most primary evidence,
    // preferring a provider that exposes primary evidence at all.
    const sorted = [...group].sort((a, b) => {
      const ap = a.provider.exposesPrimaryEvidence ? 1 : 0;
      const bp = b.provider.exposesPrimaryEvidence ? 1 : 0;
      if (ap !== bp) return bp - ap;
      return (b.provenance!.evidence.length) - (a.provenance!.evidence.length);
    });
    out.push(sorted[0]);
    for (const loser of sorted.slice(1)) {
      out.push({
        ...loser,
        stageReached: "duplicate",
        accepted: false,
        rejection: {
          code: "duplicate_of_better",
          message:
            `Same file (sha256 ${hash.slice(0, 12)}…) as the copy from ${sorted[0].provider.label}, which agrees on the licence ` +
            `and carries more primary evidence (${sorted[0].provenance!.evidence.length} items vs ${loser.provenance!.evidence.length}). ` +
            "Deduplicated in favour of the better-evidenced copy.",
        },
      });
    }
  }

  return out;
}

// ---------------------------------------------------------------------------
// Stage 7: publication validation
// ---------------------------------------------------------------------------

/** The exact `media_assets` row shape the pipeline proposes to write. */
export type ProposedAssetRow = {
  storage_path: string;
  media_type: "image";
  alt_text: string | null;
  width: number | null;
  height: number | null;
  license: string | null;
  creator: string | null;
  source_type: "public_domain_or_cc";
  asset_role: "product_photo";
  source_url: string | null;
  attribution: string | null;
  attribution_required: boolean;
  ai_generated: false;
  owned: false;
  rights_status: typeof ENGINE_MAX_RIGHTS_STATUS;
  publication_status: "private";
};

export type PublicationSafety = {
  /** True when the proposed row is correctly REFUSED by the publication gate. */
  safe: boolean;
  publishEligibility: ReturnType<typeof evaluatePublishEligibility>;
  provenanceVerdict: ReturnType<typeof evaluateProvenance>;
  explanation: string;
};

/**
 * Assert that what the engine is about to write cannot publish itself.
 *
 * This is an invariant check, not a permission check — `safe: true` means
 * "correctly blocked". A `safe: false` here is a defect in this pipeline, and
 * the caller must abort rather than proceed.
 */
export function validateEnginePublicationSafety(row: ProposedAssetRow): PublicationSafety {
  const asset: ProvenanceAsset = {
    source_type: row.source_type,
    rights_status: row.rights_status,
    license: row.license,
    creator: row.creator,
    attribution: row.attribution,
    attribution_required: row.attribution_required,
    source_url: row.source_url,
    owned: row.owned,
    ai_generated: row.ai_generated,
  };

  const publishEligibility = evaluatePublishEligibility({
    rights_status: row.rights_status,
    owned: row.owned,
    source_type: row.source_type,
  });
  const provenanceVerdict = evaluateProvenance(asset);

  const safe = !publishEligibility.allowed && !provenanceVerdict.publishable;

  return {
    safe,
    publishEligibility,
    provenanceVerdict,
    explanation: safe
      ? `The proposed row carries rights_status='${row.rights_status}', owned=false and source_type='${row.source_type}'. ` +
        `evaluatePublishEligibility() refuses it and evaluateProvenance() classifies it '${provenanceVerdict.rightsClass}' ` +
        `with ${provenanceVerdict.findings.filter((f) => f.severity === "blocker").length} blocker(s). The engine has therefore ` +
        "produced an archived, credited, unpublishable record — which is exactly the intended output. A human moves it further."
      : "INVARIANT VIOLATED: the row the engine proposes to write would clear the publication gate on its own. " +
        "The engine must never be able to publish. Abort rather than write this row.",
  };
}

/** Build the row the pipeline would write for an accepted candidate. */
export function buildProposedRow(input: {
  storagePath: string;
  altText: string | null;
  provenance: ProvenanceRecord;
}): ProposedAssetRow {
  const p = input.provenance;
  return {
    storage_path: input.storagePath,
    media_type: "image",
    alt_text: input.altText,
    width: p.width,
    height: p.height,
    license: p.licenceDeclared ?? p.licenceMetadata,
    creator: p.creator,
    source_type: "public_domain_or_cc",
    asset_role: "product_photo",
    source_url: p.sourcePageUrl,
    attribution: p.attributionText,
    attribution_required: p.attributionRequired ?? true,
    ai_generated: false,
    owned: false,
    rights_status: ENGINE_MAX_RIGHTS_STATUS,
    publication_status: "private",
  };
}

// ---------------------------------------------------------------------------
// Orchestration
// ---------------------------------------------------------------------------

/**
 * The legacy four-value status, kept because the engine job, the admin surfaces
 * and the requirement notes all read it.
 *
 * It is now DERIVED from `PipelineReport.outcome` (see `legacyStatusFor`)
 * rather than computed independently, so the coarse and the precise answer
 * cannot drift apart. The seven-state taxonomy in outcome.ts is the real one:
 * this collapses `WRONG_ENTITY_RESULTS` / `RIGHTS_UNCERTAIN` /
 * `PROVENANCE_INCOMPLETE` into one bucket, and that collapse is exactly what
 * made the `|other versions=` parser bug invisible.
 */
export type PipelineStatus =
  /** Ran to completion, at least one candidate accepted. */
  | "resolved"
  /** Ran to completion, nothing acceptable found. A LEGITIMATE result. */
  | "no_acceptable_candidate"
  /** Ran to completion, the provider genuinely had nothing. Also legitimate. */
  | "no_results"
  /** Could not run properly. NOT the same as finding nothing. */
  | "provider_unavailable";

export type PipelineReport = {
  identity: SubjectIdentity;
  status: PipelineStatus;
  /**
   * Which of the seven outcome states this search ended in, and the positive
   * evidence for that state. Read this in preference to `status`.
   */
  outcome: SearchOutcome;
  /** Every query issued, and what it returned. */
  queryLog: { query: ProviderQuery; hits: number; note: string }[];
  /** Expansions generated and refused before any request was made. */
  refusedQueries: { value: string; strategy: string; reason: string }[];
  evaluations: CandidateEvaluation[];
  ranking: RankingResult | null;
  /** The row that would be written for the winner, if any. */
  proposedRow: ProposedAssetRow | null;
  publicationSafety: PublicationSafety | null;
  /** Prose an editor can read. */
  narrative: string;
};

export type PipelineOptions = {
  maxCandidates: number;
  ranking: RankingContext;
  /** Alt text for the proposed row; the engine does not invent descriptions. */
  altTextFor?: (identity: SubjectIdentity, provenance: ProvenanceRecord) => string | null;
  /** Storage path for the proposed row; supplied by the caller that will write it. */
  storagePathFor?: (identity: SubjectIdentity, provenance: ProvenanceRecord) => string;
};

/**
 * Run the full pipeline for one subject across one or more providers.
 *
 * Note the provider list is a parameter. There is no import of any specific
 * provider in this file, and no branch anywhere that special-cases one — the
 * engine is not built around Wikimedia Commons, Commons is simply the first
 * source that passed approval.
 */
export async function runAcquisitionPipeline(
  identity: SubjectIdentity,
  providers: MediaProvider[],
  options: PipelineOptions
): Promise<PipelineReport> {
  const queryLog: PipelineReport["queryLog"] = [];
  const refusedQueries: PipelineReport["refusedQueries"] = [];
  const evaluations: CandidateEvaluation[] = [];
  /**
   * What each provider did, recorded as it happens.
   *
   * This is what makes NO_RESULTS provable rather than assumed: the classifier
   * is not handed "there are no candidates" and left to infer why, it is handed
   * each provider's own answer plus what that provider can attest about the
   * responses behind it.
   */
  const episodes: ProviderEpisode[] = [];

  const plan = expandQueries(identity);
  refusedQueries.push(...plan.rejected.map((r) => ({ value: r.value, strategy: r.strategy as string, reason: r.reason })));

  for (const provider of providers) {
    if (!provider.approval.approvedForSearch) {
      queryLog.push({
        query: { strategy: "text_search", value: "(none issued)", rationale: "", identityTokens: [] },
        hits: 0,
        note: `${provider.approval.label} is NOT approved for search: ${provider.approval.rationale}`,
      });
      episodes.push({
        approval: provider.approval,
        searched: false,
        // No request was issued, so there is no answer to record. `searched`
        // is what the classifier reads; this status is never inspected for an
        // unsearched provider, and an unsearched source is never an empty one.
        outcome: { status: "outage", detail: "not approved for search — no request was issued" },
        attestation: null,
        candidates: 0,
      });
      continue;
    }

    const search = await provider.search([...plan.strict, ...plan.broad], { maxCandidates: options.maxCandidates });
    queryLog.push(...search.queryLog);
    episodes.push({
      approval: provider.approval,
      searched: true,
      outcome: search.outcome,
      attestation: search.attestation ?? null,
      candidates: search.candidates.length,
    });

    if (search.outcome.status !== "ok" && search.outcome.status !== "no_results") {
      // A provider failure must never look like "found nothing".
      evaluations.push({
        key: `${provider.approval.id}::provider`,
        descriptor: { title: `(${provider.approval.label} unavailable)`, fileName: null, categories: [], descriptionText: null, mimeType: null },
        provider: provider.approval,
        stageReached: "entity",
        accepted: false,
        rejection: {
          code: search.outcome.status === "malformed" ? "provider_malformed" : "provider_outage",
          message:
            `${provider.approval.label} could not be searched (${search.outcome.status}: ` +
            `${"detail" in search.outcome ? search.outcome.detail : ""}). This is NOT a finding of "no photograph exists" — ` +
            "the search did not happen. Recorded distinctly so a broken source never masquerades as an empty one.",
        },
        entityMatch: null, provenance: null, rights: null,
      });
      continue;
    }

    for (const candidate of search.candidates) {
      const descriptor = descriptorOf(candidate);
      // Cheap gate first: do not spend a network round-trip resolving the
      // provenance of a file that is plainly the wrong product.
      const preMatch = assessEntityMatch(identity, descriptor);
      if (preMatch.verdict !== "confirmed") {
        evaluations.push({
          key: `${provider.approval.id}::${candidate.providerRef}`,
          descriptor, provider: provider.approval,
          stageReached: "entity", accepted: false,
          rejection: {
            code: preMatch.verdict === "ambiguous" ? "entity_ambiguous" : "entity_mismatch",
            message: preMatch.reason,
          },
          entityMatch: preMatch, provenance: null, rights: null,
        });
        continue;
      }

      const resolved = await provider.resolve(candidate);
      evaluations.push(
        evaluateCandidate({
          identity,
          descriptor: resolved.provenance ? enrichDescriptor(descriptor, resolved.provenance) : descriptor,
          provenance: resolved.provenance,
          resolveOutcome: resolved.outcome,
          provider: provider.approval,
          key: `${provider.approval.id}::${candidate.providerRef}`,
        })
      );
    }
  }

  const reconciled = reconcileDuplicates(evaluations);
  const accepted = reconciled.filter((e) => e.accepted && e.provenance && e.rights && e.entityMatch);

  const rankable: RankableCandidate[] = accepted.map((e) => ({
    key: e.key,
    descriptor: e.descriptor,
    provenance: e.provenance!,
    entityMatch: e.entityMatch!,
    rights: e.rights!,
    approval: e.provider,
  }));

  const ranking = rankable.length > 0 ? rankCandidates(rankable, options.ranking) : null;

  let proposedRow: ProposedAssetRow | null = null;
  let publicationSafety: PublicationSafety | null = null;
  if (ranking?.winner) {
    const p = ranking.winner.candidate.provenance;
    proposedRow = buildProposedRow({
      storagePath: options.storagePathFor?.(identity, p) ?? `image/pending-${p.contentHash ?? "unhashed"}`,
      altText: options.altTextFor?.(identity, p) ?? null,
      provenance: p,
    });
    publicationSafety = validateEnginePublicationSafety(proposedRow);
  }

  // The single classification point. There is no other place in this function
  // where an outcome is decided, and no branch that falls through to "found
  // nothing" — `classifySearchOutcome` either establishes a state positively or
  // returns PROVIDER_PARSE_FAILURE.
  const outcome = classifySearchOutcome({ episodes, evaluations: reconciled });
  const status: PipelineStatus = legacyStatusFor(outcome.state);

  return {
    identity,
    status,
    outcome,
    queryLog,
    refusedQueries,
    evaluations: reconciled,
    ranking,
    proposedRow,
    publicationSafety,
    narrative: buildNarrative(identity, status, outcome, reconciled, ranking),
  };
}

function descriptorOf(c: DiscoveredCandidate): CandidateDescriptor {
  return {
    title: c.title,
    fileName: c.providerRef.replace(/^File:/i, "") || null,
    categories: c.descriptors.filter((d) => /^Category:/i.test(d)),
    descriptionText: c.descriptors.filter((d) => !/^Category:/i.test(d)).join(" ") || null,
    mimeType: null,
  };
}

/**
 * Fold what resolution learned back into the descriptor before the full
 * evaluation re-runs entity matching.
 *
 * The EXIF camera model is the addition that matters: it is only available
 * after resolution, and it is what catches a photograph taken BY the subject
 * camera whose title happens not to say so.
 */
function enrichDescriptor(d: CandidateDescriptor, p: ProvenanceRecord): CandidateDescriptor {
  const exifModel = p.evidence
    .map((e) => /^EXIF Model="(.*)"$/.exec(e.detail)?.[1])
    .find((v): v is string => Boolean(v));
  return {
    ...d,
    mimeType: p.mimeType ?? d.mimeType,
    fileName: p.originalFileName ?? d.fileName,
    exifCameraModel: exifModel ?? d.exifCameraModel ?? null,
  };
}

function buildNarrative(
  identity: SubjectIdentity,
  status: PipelineStatus,
  outcome: SearchOutcome,
  evaluations: CandidateEvaluation[],
  ranking: RankingResult | null
): string {
  // The state and its justification lead, because the coarse status below is
  // the thing that once read identically for "nothing exists" and "our parser
  // is broken".
  const head =
    `OUTCOME ${outcome.state} — ${OUTCOME_MEANINGS[outcome.state]}\n` +
    outcome.because.map((b) => `  · ${b}`).join("\n");

  return `${head}\n${legacyNarrative(identity, status, evaluations, ranking)}`;
}

function legacyNarrative(
  identity: SubjectIdentity,
  status: PipelineStatus,
  evaluations: CandidateEvaluation[],
  ranking: RankingResult | null
): string {
  const byCode = new Map<string, number>();
  for (const e of evaluations) {
    if (e.rejection) byCode.set(e.rejection.code, (byCode.get(e.rejection.code) ?? 0) + 1);
  }
  const breakdown = [...byCode.entries()].map(([c, n]) => `${c}×${n}`).join(", ") || "none";

  switch (status) {
    case "resolved":
      return (
        `${identity.canonicalName}: ${evaluations.length} candidate(s) examined, ${evaluations.filter((e) => e.accepted).length} cleared every gate. ` +
        `Rejections: ${breakdown}. ${ranking?.whyItWon ?? ""}`
      );
    case "no_acceptable_candidate":
      return (
        `${identity.canonicalName}: candidates WERE found and every one was rejected (${breakdown}). ` +
        "This is a finding, not a gap — the search worked and the material is unsuitable. Do not stretch to fill a quota."
      );
    case "no_results":
      return (
        `${identity.canonicalName}: every query ran successfully and returned nothing. No usable photograph appears to exist ` +
        "at the searched providers yet. Blocked on photography, not on permission; worth a scheduled recheck rather than a negotiation."
      );
    case "provider_unavailable":
      return (
        `${identity.canonicalName}: the search DID NOT COMPLETE (${breakdown}). This must not be recorded as "nothing found" — ` +
        "the 2026-08 lesson in CLAUDE.md is that a failure indistinguishable from an empty result hides for weeks."
      );
  }
}
