// Media hierarchy — what a hero image IS, and whether it should be one.
//
// THE PROBLEM THIS ENCODES
// ------------------------
// TechCarvalho can generate its own graphics cheaply and legally, so it did:
// on 2026-08-22, 78 of 81 published articles used a generated graphic as their
// hero, and 20 of those shared just six category title cards. The site read as
// a database rather than a publication, because a reader arriving at an
// article about the PS5 saw a styled card with the word "Gaming" on it instead
// of a PlayStation.
//
// The graphics themselves are good and stay. What is wrong is using them as a
// SUBSTITUTE for showing the subject. A comparison chart earns the hero slot on
// a data-led comparison; it does not earn it on "GTA VI: what's confirmed".
//
// THE HIERARCHY
// -------------
// Ordered by how well the image answers "what does this thing actually look
// like?". Higher tiers are preferred as heroes; lower tiers are legitimate
// where they genuinely communicate something.
//
// Nothing here grants rights. Tier is a description of an asset we ALREADY
// hold with provenance recorded — it never authorises acquiring anything, and
// a higher tier is never a reason to relax verification.

export type MediaTier =
  /** A real image of the actual subject, and we hold rights to publish it. */
  | "real_subject"
  /** Official/press imagery under an explicit permission or press licence. */
  | "official_permitted"
  /** Third-party editorial imagery under a genuine licence, not necessarily
   *  of the exact subject (a lifestyle shot, a related object). */
  | "licensed_third_party"
  /** Photography TechCarvalho took. Owned outright. */
  | "original_photo"
  /** Original illustrative artwork. Clearly a rendering, never presented as a
   *  photograph or screenshot of the real thing. */
  | "original_render"
  /** Chart, diagram, timeline or spec comparison that renders real data. */
  | "data_graphic"
  /** A styled title card. Communicates the title and nothing else. */
  | "generic_graphic"
  /** No hero asset at all. */
  | "missing";

/** Preference order as a hero. Lower number = better answer to "show me". */
const TIER_RANK: Record<MediaTier, number> = {
  real_subject: 1,
  official_permitted: 2,
  licensed_third_party: 3,
  original_photo: 1, // as good as real_subject — it IS the subject, and we own it
  original_render: 4,
  data_graphic: 5,
  generic_graphic: 6,
  missing: 7,
};

export function tierRank(tier: MediaTier): number {
  return TIER_RANK[tier];
}

/** The fields classification needs. Kept structural so callers can pass a row. */
export type ClassifiableAsset = {
  source_type: string | null;
  asset_role: string | null;
  owned: boolean | null;
  ai_generated: boolean | null;
  storage_path: string | null;
  source_url: string | null;
  license: string | null;
};

// Filenames the graphic generators produce. The prefix is the most reliable
// signal of what a generated asset actually is, because asset_role was applied
// retroactively and a title card and a chart can both carry 'article_hero'.
const DATA_GRAPHIC_PREFIX = /-(cmp|comparison|chart|spec_diagram|timeline|p3)-/i;
const TITLE_CARD_PREFIX = /-hero-/i;

/**
 * Which tier an asset belongs to.
 *
 * Deliberately conservative about the top tiers: an asset only counts as
 * `real_subject` when its recorded provenance actually supports the claim.
 * Guessing upward would let an unverified image sit in the slot reserved for
 * imagery we can defend.
 */
export function classifyMediaTier(asset: ClassifiableAsset | null | undefined): MediaTier {
  if (!asset) return "missing";

  const source = (asset.source_type ?? "").toLowerCase();
  const role = (asset.asset_role ?? "").toLowerCase();
  const path = asset.storage_path ?? "";

  // Our own camera. Owned outright, no external licence to honour.
  if (source === "staff_photograph") return "original_photo";

  // Press kits carry an explicit permission, which is what separates them from
  // "an image on a manufacturer's website".
  if (source === "press_kit") return "official_permitted";

  // Generated by us. Split by what the graphic actually does.
  if (source === "tc_graphic") {
    if (DATA_GRAPHIC_PREFIX.test(path)) return "data_graphic";
    if (role === "comparison_graphic" || role === "chart" || role === "diagram") return "data_graphic";
    // A title card is a title card even when its filename names the topic:
    // it renders the headline over a pattern, not the subject.
    if (TITLE_CARD_PREFIX.test(path) || role === "article_hero" || role === "category_hero") {
      return "generic_graphic";
    }
    return "original_render";
  }

  // Externally sourced. A licence plus a source URL is the minimum for any
  // tier above `missing` — without both, provenance cannot be shown to a
  // reader, and the credit line is a licence condition.
  const externallySourced =
    source === "public_domain_or_cc" || source === "stock_licensed" ||
    source === "manufacturer" || source === "user_submitted" || source === "other";

  if (externallySourced) {
    if (!asset.source_url) return "licensed_third_party";
    // A product photograph depicts the subject by definition of its role.
    if (role === "product_photo") return "real_subject";
    return "licensed_third_party";
  }

  return "licensed_third_party";
}

// ---------------------------------------------------------------------------
// Whether a tier is an acceptable HERO for a given page
// ---------------------------------------------------------------------------

/** What the page is fundamentally about — decides what its hero owes a reader. */
export type SubjectKind =
  /** A specific physical product a reader wants to see. */
  | "product"
  /** A game, console or title a reader recognises visually. */
  | "named_media"
  /** A head-to-head. A comparison graphic genuinely belongs here. */
  | "comparison"
  /** A concept, standard or how-to with no single visual subject. */
  | "conceptual";

export type HeroVerdict = {
  acceptable: boolean;
  /** True when a better tier is realistically obtainable and worth pursuing. */
  shouldReplace: boolean;
  reason: string;
};

/**
 * Whether this tier is a defensible hero for this kind of page.
 *
 * The load-bearing judgement: a data graphic is *right* on a comparison and
 * *wrong* on a page about a thing people expect to see. A generic title card
 * is never the best available answer — but on a conceptual piece there may be
 * no better one, and that is not a defect.
 */
export function evaluateHero(tier: MediaTier, subject: SubjectKind): HeroVerdict {
  if (tier === "missing") {
    return { acceptable: false, shouldReplace: true, reason: "No hero image at all." };
  }

  // Anything that shows the real thing is always acceptable.
  if (tier === "real_subject" || tier === "official_permitted" || tier === "original_photo") {
    return { acceptable: true, shouldReplace: false, reason: `Shows the actual subject (${tier}).` };
  }

  if (subject === "comparison") {
    if (tier === "data_graphic") {
      return {
        acceptable: true, shouldReplace: false,
        reason: "A comparison graphic on a comparison page communicates the article's substance.",
      };
    }
    if (tier === "generic_graphic") {
      return {
        acceptable: false, shouldReplace: true,
        reason: "A title card on a comparison. The comparison data itself, or imagery of the things compared, would tell the reader more.",
      };
    }
    return { acceptable: true, shouldReplace: false, reason: `Acceptable on a comparison (${tier}).` };
  }

  if (subject === "product" || subject === "named_media") {
    if (tier === "data_graphic") {
      return {
        acceptable: false, shouldReplace: true,
        reason: "A chart is standing in for a picture of something the reader expects to SEE. Keep the graphic inside the article; the hero should show the subject.",
      };
    }
    if (tier === "generic_graphic") {
      return {
        acceptable: false, shouldReplace: true,
        reason: "A generic title card on a page about a specific, recognisable thing.",
      };
    }
    if (tier === "original_render") {
      return {
        acceptable: true, shouldReplace: true,
        reason: "An original render is honest but is not the subject. Replace if legitimate imagery becomes obtainable.",
      };
    }
    return { acceptable: true, shouldReplace: false, reason: `Licensed imagery (${tier}).` };
  }

  // Conceptual: standards, how-tos, explainers. Often there is genuinely
  // nothing to photograph, and a diagram may be the most useful image there is.
  if (tier === "data_graphic") {
    return {
      acceptable: true, shouldReplace: false,
      reason: "A diagram on an explainer is doing real work, not substituting for a photograph.",
    };
  }
  return {
    acceptable: true, shouldReplace: false,
    reason: "A conceptual piece with no single visual subject; a title card is a reasonable lead.",
  };
}

/**
 * Infer what a page is about from its content type and title.
 *
 * Heuristic and deliberately shallow — it decides how strictly to judge a
 * hero, never whether anything is published.
 */
export function inferSubjectKind(input: {
  contentType?: string | null;
  title: string;
  isProduct?: boolean;
}): SubjectKind {
  if (input.isProduct) return "product";
  if ((input.contentType ?? "").toLowerCase() === "comparison") return "comparison";

  const t = input.title.toLowerCase();
  if (/\bvs\.?\b|\bversus\b/.test(t)) return "comparison";

  // Named consoles, games and devices a reader pictures instantly.
  if (
    /\b(ps5|ps6|playstation|xbox|switch\s?2?|steam deck|iphone|galaxy s\d|pixel \d|rtx \d|radeon|ryzen|gta|call of duty|nintendo)\b/i.test(t)
  ) {
    return "named_media";
  }
  return "conceptual";
}
