import "server-only";
import { createClient } from "@/lib/supabase/server";
import {
  assessContent,
  findOverlaps,
  type ContentAssessment,
  type ContentSignals,
  type ContentVerdict,
} from "@/lib/content/quality-inventory";

// The editorial backlog, computed from what is actually in the database.
//
// WHY A SERVICE AND NOT A SCRIPT
// ------------------------------
// The quality inventory has existed as a one-off script whose findings lived in
// a terminal buffer and a report nobody re-runs. A backlog that has to be
// regenerated by hand is a backlog that goes stale silently, and the counts
// (54 IMPROVE, 25 KEEP, 23 sourceless) were being quoted long after the content
// they described had changed. This recomputes on every page load, so what an
// editor sees is what is true now.
//
// EVERY QUERY CHECKS ITS OWN ERROR
// --------------------------------
// and throws, which /admin/(dashboard)/error.tsx turns into a visible failure.
// The alternative — `?? []` — is precisely how this project once rendered an
// honest-looking "no problems found" for weeks while `anon` had no grants at
// all. An admin backlog that silently reads empty on failure is worse than no
// backlog, because it actively asserts there is nothing to do.
//
// MERGE IS ADVISORY AND NOTHING ACTS ON IT
// ----------------------------------------
// findOverlaps() carries hard-won safeguards: an earlier naive detector
// proposed folding a Canon 6D comparison into a PlayStation 5 article because
// both contained the words "actually", "worth" and "upgrade" — 52% of titles on
// this site contain "actually". It now requires a shared PRODUCT, a minimum of
// two significant tokens, and preserves digit-bearing model numbers so "eos"
// and "60d" survive tokenisation. Even so, nothing here merges anything: the
// page presents candidates to a person. Product and entity identity dominates
// the decision, never shared editorial vocabulary.

export type QualityOverview = {
  assessments: ContentAssessment[];
  byVerdict: Record<ContentVerdict, ContentAssessment[]>;
  /** Published pieces with no source_records row at all. */
  sourceless: ContentAssessment[];
  /** Published pieces whose lead image is a generated card, not a real photo. */
  genericHero: ContentAssessment[];
  /** Published pieces with no internal link in either direction. */
  orphans: ContentAssessment[];
  totals: {
    published: number;
    assessed: number;
    sourceless: number;
    genericHero: number;
    orphans: number;
  };
};

/** Media whose source_type marks it as a generated graphic rather than a photograph. */
const GENERATED_SOURCE_TYPES = new Set(["tc_graphic"]);

export async function getQualityOverview(): Promise<QualityOverview> {
  const supabase = await createClient();

  const [contentRes, sourcesRes, linksRes, relsRes, mediaRes, contentMediaRes] = await Promise.all([
    supabase
      .from("content_items")
      .select("id, slug, title, type, body, status")
      .eq("status", "published"),
    supabase.from("source_records").select("content_id, reliability_tier"),
    supabase.from("content_products").select("content_id, product_id"),
    supabase.from("content_relationships").select("content_id, related_content_id"),
    supabase.from("media_assets").select("id, source_type"),
    supabase.from("content_media").select("content_id, media_id, role"),
  ]);

  // Named individually so a failure says WHICH query failed. A combined
  // "something went wrong" would send the reader to the wrong table.
  for (const [label, res] of [
    ["content_items", contentRes],
    ["source_records", sourcesRes],
    ["content_products", linksRes],
    ["content_relationships", relsRes],
    ["media_assets", mediaRes],
    ["content_media", contentMediaRes],
  ] as const) {
    if (res.error) throw new Error(`quality overview: reading ${label} failed — ${res.error.message}`);
    if (res.data === null) throw new Error(`quality overview: ${label} returned null rather than rows`);
  }

  const content = contentRes.data!;
  const generatedMediaIds = new Set(
    (mediaRes.data ?? [])
      .filter((m) => GENERATED_SOURCE_TYPES.has(String(m.source_type)))
      .map((m) => m.id)
  );

  const sourceCount = new Map<string, number>();
  const primaryCount = new Map<string, number>();
  for (const s of sourcesRes.data!) {
    if (!s.content_id) continue;
    sourceCount.set(s.content_id, (sourceCount.get(s.content_id) ?? 0) + 1);
    if (s.reliability_tier === "primary") {
      primaryCount.set(s.content_id, (primaryCount.get(s.content_id) ?? 0) + 1);
    }
  }

  const productsByContent = new Map<string, string[]>();
  for (const l of linksRes.data!) {
    if (!l.content_id || !l.product_id) continue;
    productsByContent.set(l.content_id, [...(productsByContent.get(l.content_id) ?? []), l.product_id]);
  }

  // Relationships are stored one-directional and the reverse is inferred at
  // query time — the same rule product_relationships follows. A piece linked
  // TO is not an orphan just because it did not do the linking.
  const linkCount = new Map<string, number>();
  const bump = (id: string | null) => {
    if (id) linkCount.set(id, (linkCount.get(id) ?? 0) + 1);
  };
  for (const r of relsRes.data!) {
    bump(r.content_id);
    bump(r.related_content_id);
  }

  const heroIsGeneric = new Map<string, boolean>();
  for (const cm of contentMediaRes.data!) {
    if (cm.role !== "hero" || !cm.content_id) continue;
    // Any generated hero marks the piece; a piece with both a photo and a card
    // is not flagged, because the photo is what the page can show.
    const current = heroIsGeneric.get(cm.content_id);
    const generic = generatedMediaIds.has(cm.media_id);
    heroIsGeneric.set(cm.content_id, current === false ? false : generic);
  }

  const signalsBase = content.map((c) => ({
    id: c.id,
    slug: c.slug,
    title: c.title,
    contentType: c.type,
    body: c.body,
    sourceCount: sourceCount.get(c.id) ?? 0,
    primarySourceCount: primaryCount.get(c.id) ?? 0,
    linkedProductCount: (productsByContent.get(c.id) ?? []).length,
    heroIsGeneric: heroIsGeneric.get(c.id) ?? false,
    internalLinkCount: linkCount.get(c.id) ?? 0,
    productIds: productsByContent.get(c.id) ?? [],
  }));

  // Overlap detection needs the whole corpus, so it runs once over everything
  // rather than per-item.
  const overlapMap = findOverlaps(signalsBase);

  const signals: ContentSignals[] = signalsBase.map((s) => ({
    ...s,
    overlaps: overlapMap.get(s.id) ?? [],
  }));

  const assessments = signals.map(assessContent);
  const byId = new Map(assessments.map((a) => [a.id, a]));

  const byVerdict: Record<ContentVerdict, ContentAssessment[]> = {
    KEEP: [], IMPROVE: [], MERGE: [], REVIEW: [],
  };
  for (const a of assessments) byVerdict[a.verdict].push(a);

  // Ordered worst-first inside each bucket: furthest below its own intent
  // floor is the piece a limited amount of editorial time should reach first.
  for (const list of Object.values(byVerdict)) {
    list.sort((a, b) => a.words - a.floor - (b.words - b.floor));
  }

  const pick = (fn: (s: (typeof signals)[number]) => boolean) =>
    signals.filter(fn).map((s) => byId.get(s.id)!).filter(Boolean);

  const sourceless = pick((s) => s.sourceCount === 0);
  const genericHero = pick((s) => s.heroIsGeneric);
  const orphans = pick((s) => s.internalLinkCount === 0);

  return {
    assessments,
    byVerdict,
    sourceless,
    genericHero,
    orphans,
    totals: {
      published: content.length,
      assessed: assessments.length,
      sourceless: sourceless.length,
      genericHero: genericHero.length,
      orphans: orphans.length,
    },
  };
}
